# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY src/notification-api/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY src/notification-api/ .

# Expose port 80
EXPOSE 80

# Define the command to run the app
CMD ["node", "server.js"]

